apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotos
  template:
    metadata:
      labels:
        app: dotos
    spec:
      containers:
      - image: okteto.dev/dotos:latest
        name: dotos
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c8fa7720-6048-4f9f-aadb-023831fab818"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "c8fa7720-6048-4f9f-aadb-023831fab818"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
